#!/usr/bin/env node
/**
 * scripts/generate-entries.mjs
 * ----------------------------------------------------------------------------
 * Auto-discovers every SCSS partial and JS module and writes the two entry
 * files (src/scss/main.scss and src/js/main.js) so you NEVER maintain @use or
 * import lists by hand and NEVER edit config when you add a folder.
 *
 * Run modes:
 *   node scripts/generate-entries.mjs            one-shot generation
 *   node scripts/generate-entries.mjs --watch    regenerate when files OR
 *                                                 folders are added/removed
 *
 * ORDERING RULE (convention-based — no hardcoded folder list to maintain):
 *   1. FOUNDATION folders first, in this exact order if present:
 *        base -> layout -> components
 *   2. Then EVERY other discovered top-level folder, sorted alphabetically.
 *   3. Within any folder (at any depth), files sorted alphabetically.
 *   New folders need NO code change: they slot in after the foundations.
 *
 * Watch mode reacts ONLY to add/unlink/addDir/unlinkDir — i.e. when the import
 * list actually changes. Plain content edits are handled by the sass/esbuild
 * watchers, so the generator deliberately ignores 'change' events.
 * ----------------------------------------------------------------------------
 */

import { readdir, writeFile, mkdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');

const SCSS_DIR = path.join(ROOT, 'src', 'scss');
const JS_DIR = path.join(ROOT, 'src', 'js');
const SCSS_ENTRY = path.join(SCSS_DIR, 'main.scss');
const JS_ENTRY = path.join(JS_DIR, 'main.js');

// Foundation folders load first, in this order, if present. Everything else is
// alphabetical. This is a CONVENTION, not a list you maintain per-project.
const FOUNDATION_ORDER = ['base', 'layout', 'components'];

const HEADER_LINES = [
  'AUTO-GENERATED — DO NOT EDIT.',
  'Regenerated by scripts/generate-entries.mjs on every build and in watch mode.',
  'Edit the source partials/modules instead; this file is gitignored.',
];

/** Recursively collect files under `dir` that match `predicate`.
 *  Returns POSIX-style paths relative to `dir`. */
async function walk(dir, predicate, base = dir) {
  const out = [];
  let entries;
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch {
    return out; // directory may have just been removed mid-watch
  }
  for (const entry of entries) {
    const abs = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      out.push(...(await walk(abs, predicate, base)));
    } else if (entry.isFile() && predicate(entry.name)) {
      out.push(path.relative(base, abs).split(path.sep).join('/'));
    }
  }
  return out;
}

/** Sort discovered relative paths by the convention-based ordering rule. */
function orderPaths(relPaths) {
  const topRank = (rel) => {
    const top = rel.split('/')[0];
    const idx = FOUNDATION_ORDER.indexOf(top);
    // Foundations get ranks 0..n-1; everything else shares a higher rank and is
    // then disambiguated alphabetically by full path below.
    return idx === -1 ? FOUNDATION_ORDER.length : idx;
  };
  return [...relPaths].sort((a, b) => {
    const ra = topRank(a);
    const rb = topRank(b);
    if (ra !== rb) return ra - rb;
    // Same rank bucket: alphabetical by full relative path (also orders files
    // within a folder alphabetically).
    return a.localeCompare(b, 'en');
  });
}

function bannerComment(commentToken) {
  return HEADER_LINES.map((line) => `${commentToken} ${line}`).join('\n') + '\n\n';
}

/** Build src/scss/main.scss from discovered partials. */
async function generateScss() {
  // Match partials only: files beginning with "_" and ending ".scss".
  const partials = await walk(
    SCSS_DIR,
    (name) => name.startsWith('_') && name.endsWith('.scss'),
  );
  const ordered = orderPaths(partials);

  const lines = ordered.map((rel) => {
    // Strip leading "_" of the basename and the ".scss" extension for the @use path.
    const dir = path.posix.dirname(rel);
    const fileNoUnderscore = path.posix.basename(rel).replace(/^_/, '').replace(/\.scss$/, '');
    const usePath = dir === '.' ? fileNoUnderscore : `${dir}/${fileNoUnderscore}`;
    // Namespace = relative path with '/' -> '__' to avoid collisions with
    // folders containing single underscores (e.g. landing_page).
    const ns = usePath.replace(/\//g, '__');
    return `@use '${usePath}' as ${ns};`;
  });

  const body =
    bannerComment('//') +
    (lines.length
      ? lines.join('\n') + '\n'
      : '// (no partials discovered yet)\n');

  await mkdir(SCSS_DIR, { recursive: true });
  await writeFile(SCSS_ENTRY, body, 'utf8');
  return ordered.length;
}

/** Build src/js/main.js from discovered modules. */
async function generateJs() {
  // All .js under src/js EXCEPT the generated entry itself.
  const modules = (
    await walk(JS_DIR, (name) => name.endsWith('.js'))
  ).filter((rel) => rel !== 'main.js');
  const ordered = orderPaths(modules);

  // Build a safe, unique identifier per module from its relative path.
  const ids = [];
  const used = new Set();
  const importLines = ordered.map((rel) => {
    let id = rel
      .replace(/\.js$/, '')
      .replace(/[^a-zA-Z0-9]+/g, '_')
      .replace(/^_+|_+$/g, '');
    if (/^[0-9]/.test(id)) id = `m_${id}`;
    let unique = id || 'mod';
    let n = 2;
    while (used.has(unique)) unique = `${id}_${n++}`;
    used.add(unique);
    ids.push(unique);
    return `import * as ${unique} from './${rel}';`;
  });

  const body =
    bannerComment('//') +
    (importLines.length ? importLines.join('\n') + '\n\n' : '// (no modules discovered yet)\n\n') +
    `const modules = [${ids.join(', ')}];\n\n` +
    `document.addEventListener('DOMContentLoaded', () => {\n` +
    `  for (const mod of modules) {\n` +
    `    // Modules exporting init() run automatically; those without it are\n` +
    `    // still bundled above for their side effects.\n` +
    `    mod.init?.();\n` +
    `  }\n` +
    `});\n`;

  await mkdir(JS_DIR, { recursive: true });
  await writeFile(JS_ENTRY, body, 'utf8');
  return ordered.length;
}

async function generateAll(label = 'generate') {
  const [scssCount, jsCount] = await Promise.all([generateScss(), generateJs()]);
  console.log(
    `[${label}] wrote src/scss/main.scss (${scssCount} partials) and src/js/main.js (${jsCount} modules)`,
  );
}

async function generateScssLogged() {
  const n = await generateScss();
  console.log(`[watch] regenerated src/scss/main.scss (${n} partials)`);
}

async function generateJsLogged() {
  const n = await generateJs();
  console.log(`[watch] regenerated src/js/main.js (${n} modules)`);
}

async function watch() {
  await generateAll('watch:init');

  const { default: chokidar } = await import('chokidar');

  // Debounce so a burst of add/unlink events triggers a single regeneration.
  const makeDebounced = (fn, ms = 100) => {
    let t = null;
    return () => {
      clearTimeout(t);
      t = setTimeout(() => {
        fn().catch((err) => console.error('[watch] error:', err));
      }, ms);
    };
  };
  const regenScss = makeDebounced(generateScssLogged);
  const regenJs = makeDebounced(generateJsLogged);

  // IMPORTANT: only structural events. We deliberately do NOT listen to 'change'
  // — content edits are recompiled by the sass/esbuild watchers, not here.
  const STRUCTURAL = ['add', 'unlink', 'addDir', 'unlinkDir'];

  const scssWatcher = chokidar.watch(SCSS_DIR, {
    ignoreInitial: true,
    ignored: SCSS_ENTRY, // never react to our own output
  });
  const jsWatcher = chokidar.watch(JS_DIR, {
    ignoreInitial: true,
    ignored: JS_ENTRY,
  });

  for (const evt of STRUCTURAL) {
    scssWatcher.on(evt, (p) => {
      console.log(`[watch] scss ${evt}: ${path.relative(ROOT, p)}`);
      regenScss();
    });
    jsWatcher.on(evt, (p) => {
      console.log(`[watch] js ${evt}: ${path.relative(ROOT, p)}`);
      regenJs();
    });
  }

  console.log('[watch] watching src/scss and src/js for added/removed files & folders…');

  const shutdown = async () => {
    await Promise.all([scssWatcher.close(), jsWatcher.close()]);
    process.exit(0);
  };
  process.on('SIGINT', shutdown);
  process.on('SIGTERM', shutdown);
}

// ---- entrypoint ----
const isWatch = process.argv.includes('--watch');
if (!existsSync(SCSS_DIR)) await mkdir(SCSS_DIR, { recursive: true });
if (!existsSync(JS_DIR)) await mkdir(JS_DIR, { recursive: true });

if (isWatch) {
  await watch();
} else {
  await generateAll('generate');
}
